sudo: required
language: bash
services:
- docker

script:
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

- docker build -f ./Dockerfile -t vladshub/sickrage:latest .
- docker push vladshub/sickrage:latest

